import logging
from statistics import mean

from schemas.graph_state import GraphState
from core.vector_store import get_vector_store


logger = logging.getLogger(__name__)

DEFAULT_K = 5


def retrieval_agent(
    state: GraphState
) -> dict:
    """
    Retrieval Agent.

    Responsibilities:
    - Semantic retrieval from FAISS
    - Evidence collection
    - Source attribution
    - Retrieval quality metrics
    - Context deduplication
    """

    search_queries = state.get(
        "search_queries",
        []
    )

    retrieval_k = state.get(
        "retrieval_k",
        DEFAULT_K
    )

    if not search_queries:

        logger.warning(
            "No search queries generated by Research Agent."
        )

        return {
            "retrieved_context": [],
            "retrieval_sources": [],
            "best_match_score": None,
            "average_match_score": None,
            "retrieved_document_count": 0,
        }

    try:

        vector_store = get_vector_store()

        all_results = []

        for query in search_queries:

            results = (
                vector_store.similarity_search_with_score(
                    query,
                    k=retrieval_k
                )
            )

            all_results.extend(results)

        if not all_results:

            logger.warning(
                "No documents retrieved."
            )

            return {
                "retrieved_context": [],
                "retrieval_sources": [],
                "best_match_score": None,
                "average_match_score": None,
                "retrieved_document_count": 0,
            }

        # ----------------------------------
        # Sort by FAISS distance
        # Lower distance = better match
        # ----------------------------------

        all_results.sort(
            key=lambda item: item[1]
        )

        # ----------------------------------
        # Deduplicate chunks
        # ----------------------------------

        unique_chunk_content = set()

        filtered_results = []

        for doc, score in all_results:

            content_hash = hash(
                doc.page_content.strip()
            )

            if content_hash in unique_chunk_content:
                continue

            unique_chunk_content.add(
                content_hash
            )

            filtered_results.append(
                (doc, score)
            )

        # ----------------------------------
        # Cap final context size
        # ----------------------------------

        filtered_results = filtered_results[:12]

        retrieved_context = []
        retrieval_sources = []

        unique_sources = set()

        scores = []

        for doc, score in filtered_results:

            scores.append(
                float(score)
            )

            retrieved_context.append(
                doc.page_content
            )

            source_name = (
                doc.metadata.get(
                    "source",
                    "Unknown"
                )
            )

            page_number = str(
                doc.metadata.get(
                    "page_label",
                    doc.metadata.get(
                        "page",
                        "Unknown"
                    )
                )
            )

            source_key = (
                source_name,
                page_number
            )

            if source_key not in unique_sources:

                unique_sources.add(
                    source_key
                )

                retrieval_sources.append(
                    {
                        "source": source_name,
                        "page": page_number,
                    }
                )

        best_match_score = min(
            scores
        )

        average_match_score = mean(
            scores
        )

        logger.info(
            f"Retrieved {len(retrieved_context)} unique chunks. "
            f"Best score={best_match_score:.4f} "
            f"Average score={average_match_score:.4f}"
        )

        return {
            "retrieved_context":
                retrieved_context,

            "retrieval_sources":
                retrieval_sources,

            "best_match_score":
                best_match_score,

            "average_match_score":
                average_match_score,

            "retrieved_document_count":
                len(retrieved_context),
        }

    except Exception as exc:

        logger.exception(
            "Retrieval agent failed: %s",
            exc
        )

        return {
            "retrieved_context": [],
            "retrieval_sources": [],
            "best_match_score": None,
            "average_match_score": None,
            "retrieved_document_count": 0,
        }