from typing import List, Literal, Optional
from pydantic import BaseModel, Field



class ResearchAgentOutput(BaseModel):
    """
    Schema representing the output of the Research Agent.
    Translates the user's raw question into optimized search parameters.
    """

    query_intent: Literal[
        "factual",
        "comparative",
        "summary",
        "policy_lookup",
        "unknown"
    ] = Field(
        description="The categorized intent behind the user's question to guide retrieval and response generation."
    )

    search_queries: List[str] = Field(
        description="A list of optimized search queries generated for vector database retrieval."
    )


class RetrievalSourceMetadata(BaseModel):
    """
    Strict schema representing the metadata for a single retrieved chunk.
    Prevents the use of generic dictionaries for source tracking.
    """

    document_name: str = Field(
        description="The filename or title of the source document."
    )

    page_number: int = Field(
        description="The specific page number where the retrieved text is located."
    )


class RetrievalAgentOutput(BaseModel):
    """
    Schema representing the output of the Retrieval Agent.
    Contains the evidence retrieved from the vector database.
    """

    retrieved_context: List[str] = Field(
        description="A list of text chunks retrieved from the vector database."
    )

    retrieval_sources: List[RetrievalSourceMetadata] = Field(
        description="Structured metadata linking retrieved chunks back to their source documents."
    )

    best_match_score: Optional[float] = Field(
        default=None,
        description="Highest similarity score among retrieved chunks."
    )


class ResponseAgentOutput(BaseModel):
    """
    Schema representing the draft output of the Response Agent.
    This is an intermediate answer before validation.
    """

    generated_answer: str = Field(
        description="Draft answer synthesized from the retrieved evidence."
    )


class ValidationAgentOutput(BaseModel):
    """
    Schema representing the output of the Validation Agent.
    Determines whether the generated answer is sufficiently grounded in retrieved evidence.
    """

    validation_passed: bool = Field(
        description="True if the answer passed grounding and citation validation."
    )

    validation_feedback: Optional[str] = Field(
        default=None,
        description="Feedback explaining validation failures or suggested corrections."
    )

    requires_regeneration: bool = Field(
        description="Indicates whether the answer should be regenerated by the Response Agent."
    )