from typing import TypedDict, List, Optional, Literal

from schemas.agent_outputs import RetrievalSourceMetadata


class GraphState(TypedDict, total=False):
    """
    Shared state passed between LangGraph agents.

    Each agent reads relevant fields from the state and
    returns updates that are merged back into the workflow.

    Using total=False allows fields to be progressively
    populated as the workflow advances.
    """

    # ==========================================================
    # User Input
    # ==========================================================

    question: str
    """
    Original user question.
    """

    # ==========================================================
    # Guardrail Agent Outputs
    # ==========================================================

    is_allowed: bool
    """
    Whether the request passed guardrail checks.
    """

    guardrail_reason: Optional[str]
    """
    Reason for blocking the request, if applicable.
    """

    # ==========================================================
    # Research Agent Outputs
    # ==========================================================

    query_intent: Literal[
        "factual",
        "comparative",
        "summary",
        "policy_lookup",
        "unknown"
    ]
    """
    Intent classification generated by the Research Agent.
    """

    search_queries: List[str]
    """
    Optimized retrieval queries generated by the
    Research Agent.
    """

    # ==========================================================
    # Retrieval Agent Outputs
    # ==========================================================

    retrieved_context: List[str]
    """
    Retrieved document chunks selected as evidence.
    """

    retrieval_sources: List[RetrievalSourceMetadata]
    """
    Source metadata associated with retrieved chunks.
    Used for source attribution in the UI.
    """

    best_match_score: Optional[float]
    """
    Best retrieval similarity score observed during
    vector search.

    Used as a retrieval quality indicator.
    """

    # ==========================================================
    # Response Agent Outputs
    # ==========================================================

    generated_answer: Optional[str]
    """
    Draft answer generated from retrieved evidence.
    """

    # ==========================================================
    # Validation Agent Outputs
    # ==========================================================

    validation_passed: bool
    """
    Indicates whether the generated answer passed
    validation checks.
    """

    validation_feedback: Optional[str]
    """
    Feedback produced by the Validation Agent when
    regeneration is required.
    """

    requires_regeneration: bool
    """
    Determines whether the workflow should route
    back to the Response Agent.
    """

    regeneration_count: int
    """
    Tracks how many times answer generation has
    been retried.

    Acts as a circuit breaker for the validation loop.
    """