from typing import TypedDict, List, Dict, Optional, Literal


class GraphState(TypedDict, total=False):
    """
    Shared state passed between LangGraph agents.

    Each agent reads relevant fields from the state and returns
    updates that are merged back into the workflow state.

    Using total=False allows fields to be populated progressively
    as the workflow advances through each agent.
    """

    # ==========================================================
    # User Input
    # ==========================================================
    question: str
    """
    Original user question submitted to the system.
    """

    # ==========================================================
    # Guardrail Agent Outputs
    # ==========================================================
    is_allowed: bool
    """
    Whether the request passed safety, policy,
    and prompt-injection checks.
    """

    guardrail_reason: Optional[str]
    """
    Explanation when a request is blocked.
    Empty when request is allowed.
    """

    # ==========================================================
    # Research Agent Outputs
    # ==========================================================
    query_intent: Literal[
        "factual",
        "comparative",
        "summary",
        "policy_lookup",
        "unknown"
    ]
    """
    Interpreted intent of the user's query.
    Used to guide retrieval strategy.
    """

    search_queries: List[str]
    """
    Optimized search queries generated by the
    Research Agent for vector retrieval.
    """

    # ==========================================================
    # Retrieval Agent Outputs
    # ==========================================================
    retrieved_context: List[str]
    """
    Retrieved document chunks selected as evidence
    for answer generation.
    """

    retrieval_sources: List[Dict[str, str]]
    """
    Source metadata associated with retrieved chunks.

    Example:
    [
        {
            "source": "employee_handbook.pdf",
            "page": "12"
        }
    ]
    """

    best_match_score: Optional[float]
    """
    Highest similarity score returned by retrieval.

    Used to determine whether retrieved context
    is sufficiently relevant for answer generation.
    """

    # ==========================================================
    # Response Agent Outputs
    # ==========================================================
    generated_answer: Optional[str]
    """
    Draft answer generated from retrieved evidence.

    This may later be replaced by a structured
    ResponseSchema object once response schemas
    are introduced.
    """

    # ==========================================================
    # Validation Agent Outputs
    # ==========================================================
    validation_passed: bool
    """
    Indicates whether the generated answer passed
    grounding, citation, and hallucination checks.
    """

    validation_feedback: Optional[str]
    """
    Feedback produced by the Validation Agent.

    Used when answer regeneration is required.
    """

    regeneration_count: int
    """
    Tracks how many times answer generation
    has been retried.

    Acts as a circuit breaker to prevent
    infinite validation-regeneration loops.
    """